"""
###################################################################################
# Original code by Martin Sebastian Wain for YAELTEX - 2016
# Revisions by Hernan Ordiales and Franco Grassano - 2016/2017
###################################################################################

This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['kilowhat.py']
DATA_FILES = [('', ['assets']),('', ['templates']), ('', ['locales']), ('', ['style-mac.css']), ('', ['ioconfig.txt'])]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
